
/*
Business Question: 
Which appointment types have the highest patient satisfaction?

Stakeholder: Leadership of Valley Regional Medical Center

Purpose: To define the appointment types associated with the higest patient satisfaction scores. 

SQL Query: (see below)

Findings:
Average patient satisfaction remained consistent across appointment types, ranging only from 4.15-4.20.
The highest average patient satisfaction score of 4.20 was generated by Procedure appointments. 19.68% of all appointments.
Follow-up appointments had an average score of 4.18. 
Lab Work and Routine Checkup appointments had scores of 4.17. 20.5% (Lab Work) 
Lastly, Consultations had an average patient satisfaction score of 4.15. 

Business Insight:
All appointment types generate average patient satisfaction scores within .05 points of each other. 
The minimal differnce in avg patient satisfaction scores suggest that appointment types alone, do not greatly impact patient satisfaction scores. 

Recomendation:
Further investiagtion into patient data, severity level, appointment_duration_minutes, and other procedural metrics could reveal more insight into what could be mainly influencing patient satisfaction scores.  
*/

--datasets used
Select
	*
From
	appointments
;

Select
	*
From
	providers
;

--query to answer: Which appointment types have the highest patient satisfaction? 
Select
	  app.appointment_type
	, round(avg(patient_satisfaction_score),2) avg_sat_score
	, max(patient_satisfaction_score) max_sat_score
	, min(patient_satisfaction_score) min_sat_score
	, count(*) total_appointments
From
	appointments app
		inner join providers pro
			on pro.provider_id=app.provider_id
Group By
	    app.appointment_type
Order By
	avg_sat_score desc
;



/*
Business Question: 
Which patient demographic groups account for the greatest number of appointment no-shows?

Stakeholder: Leadership of Valley Regional Medical Center

Purpose:
To uncover which demographic groups generate the highest no-show rates.

SQL Query: (see below)

Findings:
There are 722 occurances of no-show appointments
The no-show occurances are grouped by demoprahics from varying totals of 25-69.
There are 3 demographc groups that have the highest appointment no-show occurances of 69 and 51. Therefore, these have the highest no-show rates of ~10%(9.5%) and 7%(7.06%).
The following are demo details on the groups with the highest no-show rates:
69 no-shows from Older Adult Males from Henderson, 51 no-shows from Older Adult Females from Henderson, and 51 Older Adults Females from Las Vegas. 



Business Insight:
The highest no-show rates of 7% and 10%, are generated from Older Adult Men and Women from Henderson and Las Vegas.
This demographic group represents approximately 24% (23.68%) of the overall no-show rate. 

Recomendation:
Further analysis into these 3 demographics regarding patient informtion, appointment type, severity level, and other operational metrics to uncover what may be causing no-show appointment status.
*/

--datasets used for this query 
Select
	*
From
	patients
;

Select
	*
From
	appointments
;

--query used to answer: Which patient demographic groups account for the greatest number of appointment no-shows?
Select
	  Count(*) total_no_show
	, pts.gender
	, pts.city
	, app.appointment_status
	, case
			when pts.age <18 then 'Under_18'
			when pts.age between 18 and 44 then '18-44'
			when pts.age between 45 and 64 then '45-64' --middle age
			when pts.age >64 then 'Older_Adults'
			else 'Group_Not_Represented'
		  end as age_group
From
	appointments app
		inner join patients pts
			on app.patient_id=pts.patient_id
Where
	app.appointment_status = 'No-Show'
Group By
	  app.appointment_status
	, pts.gender
	, age_group
	, pts.city
Order By
	total_no_show desc
;

--sum of total_no_shows: 722
Select
	sum(total_no_show)
From
	(
		Select
			  Count(*) total_no_show
			, pts.gender
			, pts.city
			, app.appointment_status
			, case
					when pts.age <18 then 'Under_18'
					when pts.age between 18 and 44 then '18-44'
					when pts.age between 45 and 64 then '45-64' --middle age
					when pts.age >64 then 'Older_Adults'
					else 'Group_Not_Represented'
				  end as age_group
		From
			appointments app
				inner join patients pts
					on app.patient_id=pts.patient_id
		Where
			app.appointment_status = 'No-Show'
		Group By
			  app.appointment_status
			, pts.gender
			, age_group
			, pts.city
		Order By
			total_no_show desc
	)
;

--Shows number of demographic groups experiencing specific total_no_show rates.
Select
	  count(total_no_show) total_demo_of_no_show
	, total_no_show
From
	(
		Select
			  Count(*) total_no_show
			, pts.gender
			, pts.city
			, app.appointment_status
			, case
					when pts.age <18 then 'Under_18'
					when pts.age between 18 and 44 then '18-44'
					when pts.age between 45 and 64 then '45-64' --middle age
					when pts.age >64 then 'Older_Adults'
					else 'Group_Not_Represented'
				  end as age_group
		From
			appointments app
				inner join patients pts
					on app.patient_id=pts.patient_id
		Where
			app.appointment_status = 'No-Show'
		Group By
			  app.appointment_status
			, pts.gender
			, age_group
			, pts.city
		Order By
			total_no_show desc
	)
Group By
	total_no_show 
;


/*
Business Question: 
Does provider Experience appear to influence patient satisfaction?

Stakeholder: 
Leadership of Valley Regional Medical Center

Purpose:
To see if providers' years of experience has an affect on overall patient satisfaction scores. 

SQL Query: (see below)

Findings:
Across the 15 categories of years of experience groups represented in the dataset, average patient satisfaction scores ranged from 4.14 to 4.22.
All experience levels were associated with at least one maximum satisfaction score of 5.0, while minimum satisfaction scores ranged from 2.0 to 2.8.

Business Insight:
Patient satisfaction remained consistently high across all years of provider experience.
Since average satisfaction scores varied by only .08 points, there is little evidence that provider experience alone has a meaningful influence on patient satisfaction.  

Recomendation:
Provider expereince does not appear to be a primary driver of patient satisfaction. 
Future analyses should investigate other factors such as appointment type, department, continuity of care, provider workload, patient characteristics, or other operational factors to better understand what influences satisfaction scores.  
*/

Select
	  prov.years_experience
	, max(patient_satisfaction_score)
	, min(patient_satisfaction_score)
	, round(avg(patient_satisfaction_score),2) as avg_satisf_score

From
	providers prov
		inner join appointments app
			on prov.provider_id=app.provider_id

Group By	 
	prov.years_experience

Order By
	avg_satisf_score desc
	--years_experience
;


Select
	*
From
	appointments
;

Select
	*
From
	providers
;


--tables used:
Select 
	*
From
	er_visits er
;

Select
	*
From
	patients pts
;

Select 
	*
From
	appointments
;



	



/*
Business Question: 
Which cities generate the highest Emergency Department utilization?
Out of the 3 cities within the datasets, Henderson generates the highest Emergency Department utilization at 1103 visits. 

Stakeholder: 
Leadership of Valley Regional Medical Center

Purpose:
To see patient cities that visit the Emergency Department the most. 

SQL Query: (see below)

Findings:
Henderson generated the highest Emergency Department utilization with 1103 ER visits. 
North Las Vegas generated 970 ER visits.
Las Vegas generated 927 visits. 

Business Insight:
Representing the largest share among the three cities in the dataset, 
Henerson residents accounted for approximately 37% of all Emergency Department visits.
North Las Vegas accounted for ~32%, while Las Vegas accounted for ~31%. 

Recomendation:
Look further into why Henderson residents account for the highest share of Emergency Department visits.
Additional analysis of patient demographics, level of severity, insurance type, and primary diagnoses may help determine wheter higher utilization reflects operational factors.
*/

Select
	  pts.city
	, count(*) as number_of_er_visits 
From
	er_visits er
		inner join patients pts
			on er.patient_id=pts.patient_id
Group By
	pts.city
;





/*
Business Question: 
Which patient age groups experience the longest Emergency Department wait times?

To define age groups, the catergories of age are referenced from healthcare industry-strandards:
0–17 (pediatrics) The dataset does not contain any patients under 18.

18–44 (young adults)

45–64 (middle-aged adults)

65+ (older adults / Medicare)


Stakeholder: 
Leadershiop of Valley Regional Medical Center

Purpose:
To see if specific age demographics experience longer wait times than others. 

SQL Query: (see below)

Findings:
Age group 45-64 experience the longest wait times averaging 77 min and a median wait time 72 min.

Business Insight:
The patient age group experiencing the longest Emergency Department wait times compared to others are ages 45-64. 
The average wait time is 77.34 minutes, the median wait time is 72 min, and the max wait time is 180 minutes. Their total ER visist is 867.
Age group 18-44 wait an average of 73.99 minutes, have a median wait time of 66 minutes, and experienced a max wait time of 179 min. Their total ER visist is 934.
Lastly Older Adults (ages 65+) wait on average 72.38 minutes, have a median wait time of 65 minutes, and experienced a max watit time of 180 mintues. Their total ER visist is 1199. 

Recomendation:
Further investigate whether the longer wait times among patients aged 45-64 are associated with visit severity, arrival time, diagnostic needs, or other operational factors. 
Since the difference in average wait times is modest, no operational change should be made based on age alone. 
*/
--Which patient age groups experience the longest Emergency Department wait times?

--The following CTE, groups the ages into 4 categories. The dataset does not contain any patients under 18. 
with patient_age_groups as (
	Select
		  er.wait_time_minutes
		, pts.age
		, case
			when pts.age <18 then 'Under_18'
			when pts.age between 18 and 44 then '18-44'
			when pts.age between 45 and 64 then '45-64' --middle age
			when pts.age >64 then 'Older_Adults'
			else 'Group_Not_Represented'
		  end as age_group
	From
		er_visits er
			inner join patients pts
				on er.patient_id=pts.patient_id
)
--Then from the CTE, I select the fields I want displayed and group findings by age groups.
Select
	  age_group
	, count(*) as total_er_visits
	, round(avg(wait_time_minutes),2) as average_wait_time_minutes 
	--round((),2) allows me to take a value and only go up to 2 decimal places
	, percentile_cont(.5)
		within group(order by wait_time_minutes) as median_wait_time
	, max(wait_time_minutes) as max_wait_time_minutes
From
	patient_age_groups
Group By
	age_group
Order By
	average_wait_time_minutes desc
;
